version: '3.7'

services:
  p1mqtt:
    image: revenberg/dockerp1mqtt    
    container_name: p1mqtt
    environment:
      - MQTT_ADDRESS=192.168.2.80
      - MQTT_PORT=1883
      - MQTT_TOPIC=reading/p1
      - LOG_LEVEL=DEBUG

    restart: always
    depends_on:
      - mqttp1
    restart: always
    links:
      - mqttp1
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  mqttp1:
    image: "eclipse-mosquitto:latest"
    container_name: mqttp1
    environment:
      - TZ=Europe/Amsterdam
      - "MQTT_BROKER_URL=mqtt://127.0.0.1"      
    ports:
      - 1883:1883
      - 9001:9001
    user: "1000:1000"
    volumes:
      - /var/docker-compose/data/mqtt/config:/mosquitto/config
      - /var/docker-compose/data/mqtt/data:/mosquitto/data
      - /var/docker-compose/data/mqtt/log:/mosquitto/log
    restart: always
    network_mode: host